jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image (no push yet)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .devcontainer/Dockerfile
          load: true
          tags: test/dev-stack:ci

      - name: Run sanity tests
        run: |
          docker run --rm test/dev-stack:ci bash -c "
            echo '--- Python ---' &&
            python3 -c 'import sys; print(sys.version)' &&
            python3 -c 'import numpy, pandas; print(\"NumPy:\", numpy.__version__, \"Pandas:\", pandas.__version__)' &&
            echo '--- C++ ---' &&
            g++ --version &&
            echo '#include <iostream>\nint main(){std::cout<<\"C++ OK\";}' > test.cpp &&
            g++ test.cpp -o test && ./test &&
            echo '--- Java ---' &&
            java -version &&
            echo 'class Main{public static void main(String[]a){System.out.println(\"Java OK\");}}' > Main.java &&
            javac Main.java && java Main &&
            echo '--- Verilog ---' &&
            iverilog -V
          "

      - name: Push image if tests pass
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dev-stack:latest
            ghcr.io/${{ github.repository_owner }}/dev-stack:v1.0.0
