jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Enable BuildKit (containerd) by installing Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver: docker-container

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Dev image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .devcontainer/Dockerfile
          target: dev
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dev-stack:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Runtime image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .devcontainer/Dockerfile
          target: runtime
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dev-stack:runtime
          cache-from: type=gha
          cache-to: type=gha,mode=max
