      - name: Run TA-Lib & pandas-ta sanity tests
        run: |
          docker run --rm test/dev-stack:ci bash -c "
            python3 - <<'PYCODE'
import numpy as np
import talib
import pandas_ta as ta

# TA-Lib RSI
print('TA-Lib RSI:', talib.RSI(np.arange(1, 10, dtype=float), timeperiod=3))

# pandas-ta RSI
print('pandas-ta RSI:', ta.rsi(np.arange(1, 10, dtype=float), length=3).tolist())

# pandas-ta coverage
print('pandas-ta indicators available:', len(ta.CommonIndicators))
PYCODE
          "
